In [1]:
import torch

In [3]:
batch_size = 4
seq_len = 3
input_size = 4
hidden_size = 2

In [7]:
cell = torch.nn.RNNCell(input_size=input_size, hidden_size=hidden_size)
# 调用时: hidden = cell(input, hidden)
# input of shape(batch, input_size)
# hidden of shape(batch, hidden_size)
# dataset.shape(seq_len, batch_size, input_size)

In [9]:
dataset = torch.randn(seq_len, batch_size, input_size) # 生成一个服从标准正态分布的张量
hidden = torch.zeros(batch_size, hidden_size) # 生成一个指定大小的零张量

In [11]:
for idx, input in enumerate(dataset):
    print('='*20, idx, '='*20)
    print('Input size:', input.shape)

    hidden = cell(input, hidden)

    print('outputs size:', hidden.shape)
    print(hidden)

==================== 0 ====================
Input size: torch.Size([4, 4])
outputs size: torch.Size([4, 2])
tensor([[ 0.8168, -0.6119],
        [-0.4277,  0.8107],
        [ 0.4269, -0.7008],
        [ 0.1135, -0.4818]], grad_fn=<TanhBackward0>)
==================== 1 ====================
Input size: torch.Size([4, 4])
outputs size: torch.Size([4, 2])
tensor([[-0.2399, -0.0936],
        [-0.9617,  0.4981],
        [-0.8433,  0.8990],
        [-0.5470,  0.8256]], grad_fn=<TanhBackward0>)
==================== 2 ====================
Input size: torch.Size([4, 4])
outputs size: torch.Size([4, 2])
tensor([[-0.2637,  0.5738],
        [ 0.5814, -0.6486],
        [-0.7880,  0.0061],
        [-0.8451,  0.6650]], grad_fn=<TanhBackward0>)
